In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read future tways and local routes gtfs

myfolder = './output/future/road/4TOD/'

routes_road = pd.read_csv(myfolder + 'routes.txt')
shapes_road = pd.read_csv(myfolder + 'shapes.txt')
trips_road = pd.read_csv(myfolder + 'trips.txt')
stoptimes_road = pd.read_csv(myfolder + 'stop_times.txt')
stops_road = pd.read_csv(myfolder + 'stops.txt')

In [3]:
# Read Middleton Grange routes gtfs

routes_mg = pd.read_csv('./input/gtfs_MG_all_indiv_freq10/routes.txt')
shapes_mg = pd.read_csv('./input/gtfs_MG_all_indiv_freq10/shapes.txt')
trips_mg = pd.read_csv('./input/gtfs_MG_all_indiv_freq10/trips.txt')
stoptimes_mg = pd.read_csv('./input/gtfs_MG_all_indiv_freq10/stop_times.txt')
stops_mg = pd.read_csv('./input/gtfs_MG_all_indiv_freq10/stops.txt')

In [4]:
# Read future rail gtfs

cal_rail = pd.read_csv('./output/future/rail/calendar.txt')
routes_rail = pd.read_csv('./output/future/rail/routes.txt')
shapes_rail = pd.read_csv('./output/future/rail/shapes.txt')
trips_rail = pd.read_csv('./output/future/rail/trips.txt')
stoptimes_rail = pd.read_csv('./output/future/rail/stop_times.txt')
stops_rail = pd.read_csv('./output/future/rail/stops.txt')

In [5]:
# Read current gtfs

agency_current = pd.read_csv('./output/current_edited/agency.txt')
calendardates_current = pd.read_csv('./output/current_edited/calendar_dates.txt')
calendar_current = pd.read_csv('./output/current_edited/calendar.txt')
routes_current = pd.read_csv('./output/current_edited/routes.txt')
shapes_current = pd.read_csv('./output/current_edited/shapes.txt')
trips_current = pd.read_csv('./output/current_edited/trips.txt')
stoptimes_current = pd.read_csv('./output/current_edited/stop_times.txt')
stops_current = pd.read_csv('./output/current_edited/stops.txt')

/Users/hemarayaprolu/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (0,3,5,10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

### Calendar

In [6]:
cal_rail

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
0,mtwtf,1,1,1,1,1,0,0,20200702,20200930

In [7]:
cal_rail['service_id'] = 'mtwtfss'
cal_rail['saturday'] = '1'
cal_rail['sunday'] = '1'
cal_rail

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
0,mtwtfss,1,1,1,1,1,1,1,20200702,20200930

In [8]:
calendar_current['start_date'].median()

20200702.0

In [9]:
calendar_current['end_date'].median()

20200930.0

In [10]:
# Join the two

print(len(calendar_current))
calendar_combined = calendar_current.append(cal_rail, ignore_index=True)
print(len(calendar_combined))

2159
2160

In [11]:
# # Change year to 2056

# calendar_combined['start_date'] = calendar_combined['start_date'].astype(str)
# calendar_combined['start_date'] = calendar_combined['start_date'].str.replace('2020','2056')
# calendar_combined['end_date'] = calendar_combined['end_date'].astype(str)
# calendar_combined['end_date'] = calendar_combined['end_date'].str.replace('2020','2056')

In [12]:
calendar_combined.tail()

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
2155,TA+r4385+38,1,1,1,1,1,1,1,20200702,20200930
2156,TA+r4387+38,1,1,1,1,1,1,1,20200702,20200930
2157,TA+r4389+38,1,1,1,1,1,1,0,20200702,20200930
2158,TA+r4284+38,0,0,0,0,1,1,0,20200702,20200930
2159,mtwtfss,1,1,1,1,1,1,1,20200702,20200930

In [13]:
calendar_combined['start_date'].unique()

array([20200708, 20200711, 20200706, 20200704, 20200715, 20200703,
       20200718, 20200702, 20200705, 20200720])

In [14]:
calendar_combined['end_date'].unique()

array([20200708, 20200712, 20200709, 20200704, 20200716, 20200703,
       20200719, 20200705, 20201001, 20200930])

### Routes

In [15]:
# Check for T2
routes_current.loc[routes_current['route_id'].str.contains('T2')]

Empty DataFrame
Columns: [route_id, agency_id, route_short_name, route_long_name, route_desc, route_type, route_color, route_text_color, exact_times]
Index: []

In [16]:
# Check for Metro
routes_current.loc[routes_current['route_desc']=='Sydney Metro Network']

Empty DataFrame
Columns: [route_id, agency_id, route_short_name, route_long_name, route_desc, route_type, route_color, route_text_color, exact_times]
Index: []

In [17]:
# Join the two

print(len(routes_current))
print(len(routes_rail))
print(len(routes_road))
print(len(routes_mg))
routes_combined = routes_current.append(routes_rail, ignore_index=True).append(routes_road, ignore_index=True).append(routes_mg, ignore_index=True)
print(len(routes_combined))

6611
22
66
6
6705

### Shapes

In [18]:
# Join

print(len(shapes_current))
print(len(shapes_rail))
print(len(shapes_road))
print(len(shapes_mg))
shapes_combined = shapes_current.append(shapes_rail, ignore_index=True).append(shapes_road, ignore_index=True).append(shapes_mg, ignore_index=True)
print(len(shapes_combined))

8198121
8396
16976
2407
8225900

### Stop times

In [19]:
stoptimes_current.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint,stop_note
0,2.AA70.1-10H-U-sj2-2.1.R,10:09:00,10:09:00,233312,1,NaN,0,0,0.00,1,NaN
1,2.AA70.1-10H-U-sj2-2.1.R,10:52:00,10:52:00,233011,2,NaN,0,0,50450.60,1,NaN
2,2.AA70.1-10H-U-sj2-2.1.R,11:34:00,11:34:00,232021,3,NaN,0,0,97416.41,1,NaN
3,1.AA70.1-10H-U-sj2-2.2.H,08:50:00,08:50:00,232021,1,NaN,0,0,0.00,1,NaN
4,1.AA70.1-10H-U-sj2-2.2.H,09:35:00,09:35:00,233012,2,NaN,0,0,47346.57,1,NaN

In [20]:
stoptimes_rail.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint,stop_note
0,L-PLR1-CLFD-WSMD_T1,04:30:00,04:30:00,2056016162,1,NaN,NaN,NaN,0.019,1,NaN
1,L-PLR1-CLFD-WSMD_T1,04:35:00,04:35:00,2056016152,2,NaN,NaN,NaN,1.663,0,NaN
2,L-PLR1-CLFD-WSMD_T1,04:39:00,04:39:00,2056016142,3,NaN,NaN,NaN,3.084,0,NaN
3,L-PLR1-CLFD-WSMD_T1,04:42:00,04:42:00,2056016132,4,NaN,NaN,NaN,3.920,0,NaN
4,L-PLR1-CLFD-WSMD_T1,04:43:00,04:43:00,2056016172,5,NaN,NaN,NaN,4.335,0,NaN

In [21]:
stoptimes_road.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint,stop_note
0,10th-ASTH-CSLA_T1,04:30:00,04:30:00,20200814260,1,NaN,NaN,NaN,0.048,1,NaN
1,10th-ASTH-CSLA_T1,04:37:00,04:37:00,20200814198,2,NaN,NaN,NaN,3.973,0,NaN
2,10th-ASTH-CSLA_T1,04:39:00,04:39:00,20200814202,3,NaN,NaN,NaN,5.272,0,NaN
3,10th-ASTH-CSLA_T1,04:42:00,04:42:00,20200814210,4,NaN,NaN,NaN,6.720,0,NaN
4,10th-ASTH-CSLA_T1,04:44:00,04:44:00,20200814214,5,NaN,NaN,NaN,7.954,0,NaN

In [22]:
stoptimes_mg.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint,stop_note
0,EdmondsonPark-MG_T1,04:25:00,04:25:00,202008254,1,NaN,NaN,NaN,22.250,1,NaN
1,EdmondsonPark-MG_T1,04:27:00,04:27:00,202008255,2,NaN,NaN,NaN,747.214,0,NaN
2,EdmondsonPark-MG_T1,04:28:00,04:28:00,202008256,3,NaN,NaN,NaN,1326.937,0,NaN
3,EdmondsonPark-MG_T1,04:30:00,04:30:00,2170440,4,NaN,NaN,NaN,2362.249,0,NaN
4,EdmondsonPark-MG_T1,04:33:00,04:33:00,2170456,5,NaN,NaN,NaN,3323.565,0,NaN

In [23]:
stoptimes_rail['shape_dist_traveled'] = stoptimes_rail['shape_dist_traveled']*1000
stoptimes_rail.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint,stop_note
0,L-PLR1-CLFD-WSMD_T1,04:30:00,04:30:00,2056016162,1,NaN,NaN,NaN,19.0,1,NaN
1,L-PLR1-CLFD-WSMD_T1,04:35:00,04:35:00,2056016152,2,NaN,NaN,NaN,1663.0,0,NaN
2,L-PLR1-CLFD-WSMD_T1,04:39:00,04:39:00,2056016142,3,NaN,NaN,NaN,3084.0,0,NaN
3,L-PLR1-CLFD-WSMD_T1,04:42:00,04:42:00,2056016132,4,NaN,NaN,NaN,3920.0,0,NaN
4,L-PLR1-CLFD-WSMD_T1,04:43:00,04:43:00,2056016172,5,NaN,NaN,NaN,4335.0,0,NaN

In [24]:
stoptimes_road['shape_dist_traveled'] = stoptimes_road['shape_dist_traveled']*1000
stoptimes_road.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint,stop_note
0,10th-ASTH-CSLA_T1,04:30:00,04:30:00,20200814260,1,NaN,NaN,NaN,48.0,1,NaN
1,10th-ASTH-CSLA_T1,04:37:00,04:37:00,20200814198,2,NaN,NaN,NaN,3973.0,0,NaN
2,10th-ASTH-CSLA_T1,04:39:00,04:39:00,20200814202,3,NaN,NaN,NaN,5272.0,0,NaN
3,10th-ASTH-CSLA_T1,04:42:00,04:42:00,20200814210,4,NaN,NaN,NaN,6720.0,0,NaN
4,10th-ASTH-CSLA_T1,04:44:00,04:44:00,20200814214,5,NaN,NaN,NaN,7954.0,0,NaN

In [25]:
# Join

print(len(stoptimes_current))
print(len(stoptimes_rail))
print(len(stoptimes_road))
print(len(stoptimes_mg))
stoptimes_combined = stoptimes_current.append(stoptimes_rail, ignore_index=True).append(stoptimes_road, ignore_index=True).append(stoptimes_mg, ignore_index=True)
print(len(stoptimes_combined))

4332646
57748
1184536
23108
5598038

In [26]:
# Edit data types (to avoid errors during validation)

stoptimes_combined['pickup_type'] = stoptimes_combined['pickup_type'].apply(lambda x: str(int(x)) if x>=0 else '')
stoptimes_combined['drop_off_type'] = stoptimes_combined['drop_off_type'].apply(lambda x: str(int(x)) if x>=0 else '')

In [27]:
stoptimes_combined['pickup_type'].unique()

array(['0', '1', ''], dtype=object)

In [28]:
stoptimes_combined['drop_off_type'].unique()

array(['0', '1', ''], dtype=object)

### Trips

In [29]:
trips_rail['service_id'].unique()

array(['mtwtf'], dtype=object)

In [30]:
trips_rail['service_id'] = 'mtwtfss'
trips_rail.head()

,route_id,service_id,trip_id,shape_id,trip_headsign,direction_id,block_id,wheelchair_accessible,route_direction,trip_note,bikes_allowed
0,L-PLR1-CLFD-WSMD,mtwtfss,L-PLR1-CLFD-WSMD_T1,L-PLR1-CLFD-WSMD,Westmead,0,NaN,NaN,Carlingford - Westmead,NaN,NaN
1,L-PLR1-CLFD-WSMD,mtwtfss,L-PLR1-CLFD-WSMD_T2,L-PLR1-CLFD-WSMD,Westmead,0,NaN,NaN,Carlingford - Westmead,NaN,NaN
2,L-PLR1-CLFD-WSMD,mtwtfss,L-PLR1-CLFD-WSMD_T3,L-PLR1-CLFD-WSMD,Westmead,0,NaN,NaN,Carlingford - Westmead,NaN,NaN
3,L-PLR1-CLFD-WSMD,mtwtfss,L-PLR1-CLFD-WSMD_T4,L-PLR1-CLFD-WSMD,Westmead,0,NaN,NaN,Carlingford - Westmead,NaN,NaN
4,L-PLR1-CLFD-WSMD,mtwtfss,L-PLR1-CLFD-WSMD_T5,L-PLR1-CLFD-WSMD,Westmead,0,NaN,NaN,Carlingford - Westmead,NaN,NaN

In [31]:
trips_road['service_id'].unique()

array(['mtwtfss'], dtype=object)

In [32]:
trips_mg['service_id'].unique()

array(['mtwtfss'], dtype=object)

In [33]:
# Join

print(len(trips_current))
print(len(trips_rail))
print(len(trips_road))
print(len(trips_mg))
trips_combined = trips_current.append(trips_rail, ignore_index=True).append(trips_road, ignore_index=True).append(trips_mg, ignore_index=True)
print(len(trips_combined))

147660
2856
58662
654
209832

In [34]:
# Edit data types (to avoid errors during validation)

trips_combined['wheelchair_accessible'] = trips_combined['wheelchair_accessible'].apply(lambda x: str(int(x)) if x>=0 else '')
trips_combined['bikes_allowed'] = trips_combined['bikes_allowed'].apply(lambda x: str(int(x)) if x>=0 else '')

In [35]:
trips_combined['wheelchair_accessible'].unique()

array(['1', '2', ''], dtype=object)

In [36]:
trips_combined['bikes_allowed'].unique()

array([''], dtype=object)

### Stops

In [37]:
# Join

print(len(stops_current))
print(len(stops_rail))
print(len(stops_road))
print(len(stops_mg))
stops_combined = stops_current.append(stops_rail, ignore_index=True).append(stops_road, ignore_index=True).append(stops_mg, ignore_index=True)
print(len(stops_combined))

44821
429
1216
212
46678

In [38]:
# Drop duplicates (parent stations would be repeating)

print(len(stops_combined))
stops_combined['stop_id'] = stops_combined['stop_id'].astype(str)
stops_combined['stop_name'] = stops_combined['stop_name'].astype(str)
stops_combined = stops_combined.drop_duplicates(subset=['stop_id','stop_name'], keep='first')
print(len(stops_combined))

46678
45389

In [39]:
# Edit data types (to avoid errors during validation)

stops_combined['location_type'] = stops_combined['location_type'].apply(lambda x: str(int(x)) if x>=0 else '')
stops_combined['location_type'].unique()

array(['', '1'], dtype=object)

### Write out combined files

In [40]:
agency_current.to_csv('./output/combined/agency.txt', index=False)
calendardates_current.to_csv('./output/combined/calendar_dates.txt', index=False)
calendar_combined.to_csv('./output/combined/calendar.txt', index=False)
routes_combined.to_csv('./output/combined/routes.txt', index=False)
shapes_combined.to_csv('./output/combined/shapes.txt', index=False)
stoptimes_combined.to_csv('./output/combined/stop_times.txt', index=False)
trips_combined.to_csv('./output/combined/trips.txt', index=False)
stops_combined.to_csv('./output/combined/stops.txt', index=False)