In [1]:
import pandas as pd
import numpy as np
import geo.sphere

## Future rail lines

In [2]:
routeShapes = pd.read_csv('./Shapes/FutureRailRouteShapes.csv')
routeShapes.head()

,shape_id,begin,end,shape_lat,shape_lon,shape_pt_s,shape_dist,route_shor,route_long,route_desc,mode,vertex_ind,vertex_par,vertex_p_1,distance,angle
0,2-T2-sj2-22.76.H,1.0,863.0,-33.884308,151.207152,863.0,571893.354904,T2,T2 Inner West and Leppington Line,Sydney Trains Network,Train,0,0,0,0.000000,30.239691
1,2-T2-sj2-22.76.H,1.0,863.0,-33.884000,151.207376,863.0,571893.354904,T2,T2 Inner West and Leppington Line,Sydney Trains Network,Train,1,0,1,39.954442,29.157437
2,2-T2-sj2-22.76.H,1.0,863.0,-33.883808,151.207504,863.0,571893.354904,T2,T2 Inner West and Leppington Line,Sydney Trains Network,Train,2,0,2,64.320265,25.527905
3,2-T2-sj2-22.76.H,1.0,863.0,-33.883688,151.207568,863.0,571893.354904,T2,T2 Inner West and Leppington Line,Sydney Trains Network,Train,3,0,3,78.887213,24.575107
4,2-T2-sj2-22.76.H,1.0,863.0,-33.883480,151.207696,863.0,571893.354904,T2,T2 Inner West and Leppington Line,Sydney Trains Network,Train,4,0,4,104.818387,21.020924

In [3]:
routeShapes['shape_id'].unique()

array(['2-T2-sj2-22.76.H', '2-T2-sj2-22.9.R', '3-M-sj2-1.1.H',
       '3-M-sj2-1.2.R', 'M-C-1', 'M-C-2', 'M-W-1', 'M-W-2', 'M-NS-RL-1',
       'M-NS-RL-2', 'M-SW-RL-1', 'M-SW-RL-2', 'M-SM-TW-1', 'M-SM-TW-2',
       'M-P-WSA-1', 'M-P-WSA-2', 'M-P-E-1', 'M-P-E-2', 'M-P-B-K-1',
       'M-P-B-K-2', 'M-B-L-1', 'M-B-L-2', 'M-W-P-Z-1', 'M-W-P-Z-2',
       'M_Z_M_1', 'M_Z_M_2', 'MSW_1', 'MSW_2', '20560161', '20560162',
       '20560171', '20560172', 'M-P-1', 'M-P-2', 'M-P-BV-T-1',
       'M-P-BV-T-2', 'M-P-N-1', 'M-P-N-2', 'LP-C-B1', 'LP-C-B2',
       'M-C-E-1', 'M-C-E-2'], dtype=object)

In [4]:
# Metro route 1 (Liverpool - Bankstown - Chatswood - Tallawong)

route1h = routeShapes.loc[routeShapes['shape_id']=='M-B-L-2'].sort_values('vertex_ind') # Liverpool to Bankstown
route1h = route1h.append(routeShapes.loc[routeShapes['shape_id']=='MSW_2'].sort_values('vertex_ind')) # Bankstown to Sydenham
route1h = route1h.append(routeShapes.loc[routeShapes['shape_id']=='M-C-2'].sort_values('vertex_ind')) # Sydenham to Chatswood
route1h = route1h.append(routeShapes.loc[routeShapes['shape_id']=='3-M-sj2-1.1.H'].sort_values('vertex_ind')) # Chatswood to Tallawong
route1h = route1h.reset_index(drop=True)
route1h['shape_pt_sequence'] = route1h.index+1
route1h['shape_id'] = 'M-1-LVPL-TLWG'

route1r = routeShapes.loc[routeShapes['shape_id']=='3-M-sj2-1.2.R'].sort_values('vertex_ind') # Tallawong to Chatswood 
route1r = route1r.append(routeShapes.loc[routeShapes['shape_id']=='M-C-1'].sort_values('vertex_ind')) # Chatswood to Sydenham 
route1r = route1r.append(routeShapes.loc[routeShapes['shape_id']=='MSW_1'].sort_values('vertex_ind')) # Sydenham to Bankstown
route1r = route1r.append(routeShapes.loc[routeShapes['shape_id']=='M-B-L-1'].sort_values('vertex_ind')) # Bankstown to Liverpool
route1r = route1r.reset_index(drop=True)
route1r['shape_pt_sequence'] = route1r.index+1
route1r['shape_id'] = 'M-1-TLWG-LVPL'

route1 = route1h.append(route1r)
route1 = route1[['shape_id','shape_lat','shape_lon','shape_pt_sequence','distance']]
route1

           shape_id  shape_lat   shape_lon  shape_pt_sequence      distance
0     M-1-LVPL-TLWG -33.926205  150.926481                  1      0.000000
1     M-1-LVPL-TLWG -33.924733  150.927766                  2    201.946390
2     M-1-LVPL-TLWG -33.924634  150.927918                  3    219.793138
3     M-1-LVPL-TLWG -33.924505  150.928330                  4    260.493352
4     M-1-LVPL-TLWG -33.924507  150.928448                  5    271.376641
...             ...        ...         ...                ...           ...
1069  M-1-TLWG-LVPL -33.924526  150.928899               1070   9966.382350
1070  M-1-TLWG-LVPL -33.924516  150.928339               1071  10018.129881
1071  M-1-TLWG-LVPL -33.924641  150.927935               1072  10058.029810
1072  M-1-TLWG-LVPL -33.924750  150.927774               1073  10077.186955
1073  M-1-TLWG-LVPL -33.926219  150.926497               1074  10278.362942

[2080 rows x 5 columns]

In [5]:
# Metro route 2 (Bankstown - Chatswood - Epping)

route2h = routeShapes.loc[routeShapes['shape_id']=='MSW_2'].sort_values('vertex_ind') # Bankstown to Sydenham
route2h = route2h.append(routeShapes.loc[routeShapes['shape_id']=='M-C-2'].sort_values('vertex_ind')) # Sydenham to Chatswood
route2h = route2h.append(routeShapes.loc[routeShapes['shape_id']=='M-C-E-1'].sort_values('vertex_ind')) # Chatswood to Epping
route2h = route2h.reset_index(drop=True)
route2h['shape_pt_sequence'] = route2h.index+1
route2h['shape_id'] = 'M-2-BKTN-EPNG'

route2r = routeShapes.loc[routeShapes['shape_id']=='M-C-E-2'].sort_values('vertex_ind') # Epping to Chatswood
route2r = route2r.append(routeShapes.loc[routeShapes['shape_id']=='M-C-1'].sort_values('vertex_ind')) # Chatswood to Sydenham
route2r = route2r.append(routeShapes.loc[routeShapes['shape_id']=='MSW_1'].sort_values('vertex_ind')) # Sydenham to Bankstown
route2r = route2r.reset_index(drop=True)
route2r['shape_pt_sequence'] = route2r.index+1
route2r['shape_id'] = 'M-2-EPNG-BKTN'

route2 = route2h.append(route2r)
route2 = route2[['shape_id','shape_lat','shape_lon','shape_pt_sequence','distance']]
route2

          shape_id  shape_lat   shape_lon  shape_pt_sequence      distance
0    M-2-BKTN-EPNG -33.917893  151.033564                  1      0.000000
1    M-2-BKTN-EPNG -33.917809  151.034344                  2     72.745649
2    M-2-BKTN-EPNG -33.917768  151.034830                  3    117.946290
3    M-2-BKTN-EPNG -33.917733  151.035228                  4    154.928023
4    M-2-BKTN-EPNG -33.917732  151.035401                  5    170.961876
..             ...        ...         ...                ...           ...
752  M-2-EPNG-BKTN -33.917905  151.034854                753  13268.450694
753  M-2-EPNG-BKTN -33.917935  151.034407                754  13309.942209
754  M-2-EPNG-BKTN -33.917946  151.034233                755  13325.987755
755  M-2-EPNG-BKTN -33.917968  151.033636                756  13381.323350
756  M-2-EPNG-BKTN -33.917968  151.033619                757  13382.831865

[1436 rows x 5 columns]

In [6]:
# Metro route 3a (Maroubra - Zetland - The Bays - Parramatta - Western Sydney International Airport)

route3ah = routeShapes.loc[routeShapes['shape_id']=='M_Z_M_2'].sort_values('vertex_ind') # Maroubra to Zetland
route3ah = route3ah.append(routeShapes.loc[routeShapes['shape_id']=='M-W-P-Z-2'].sort_values('vertex_ind')) # Zetland to The Bays Precinct
route3ah = route3ah.append(routeShapes.loc[routeShapes['shape_id']=='M-W-1'].sort_values('vertex_ind')) # The Bays Precinct to Parramatta
route3ah = route3ah.append(routeShapes.loc[routeShapes['shape_id']=='M-P-WSA-1'].sort_values('vertex_ind')) # Parramatta to WSI Airport
route3ah = route3ah.reset_index(drop=True)
route3ah['shape_pt_sequence'] = route3ah.index+1
route3ah['shape_id'] = 'M-3a-MBRA-WSIA'

route3ar = routeShapes.loc[routeShapes['shape_id']=='M-P-WSA-2'].sort_values('vertex_ind') # WSI Airport to Parramatta
route3ar = route3ar.append(routeShapes.loc[routeShapes['shape_id']=='M-W-2'].sort_values('vertex_ind')) # Parramatta to The Bays Precinct
route3ar = route3ar.append(routeShapes.loc[routeShapes['shape_id']=='M-W-P-Z-1'].sort_values('vertex_ind')) # The Bays Precinct to Zetland
route3ar = route3ar.append(routeShapes.loc[routeShapes['shape_id']=='M_Z_M_1'].sort_values('vertex_ind')) # Zetland to Maroubra
route3ar = route3ar.reset_index(drop=True)
route3ar['shape_pt_sequence'] = route3ar.index+1
route3ar['shape_id'] = 'M-3a-WSIA-MBRA'

route3a = route3ah.append(route3ar)
route3a = route3a[['shape_id','shape_lat','shape_lon','shape_pt_sequence','distance']]
route3a

           shape_id  shape_lat   shape_lon  shape_pt_sequence     distance
0    M-3a-MBRA-WSIA -33.965844  151.250771                  1     0.000000
1    M-3a-MBRA-WSIA -33.944497  151.242406                  2  2490.621707
2    M-3a-MBRA-WSIA -33.940453  151.241039                  3  2956.651676
3    M-3a-MBRA-WSIA -33.934270  151.238895                  4  3670.484049
4    M-3a-MBRA-WSIA -33.923089  151.234705                  5  4969.736715
..              ...        ...         ...                ...          ...
364  M-3a-WSIA-MBRA -33.922921  151.234844                365  2560.512017
365  M-3a-WSIA-MBRA -33.924601  151.235426                366  2754.412480
366  M-3a-WSIA-MBRA -33.933906  151.238936                367  3836.355092
367  M-3a-WSIA-MBRA -33.945197  151.242877                368  5140.561752
368  M-3a-WSIA-MBRA -33.965728  151.250959                369  7537.067133

[698 rows x 5 columns]

In [7]:
# Metro route 3b (Maroubra - Zetland - The Bays - Parramatta)

route3bh = routeShapes.loc[routeShapes['shape_id']=='M_Z_M_2'].sort_values('vertex_ind') # Maroubra to Zetland
route3bh = route3bh.append(routeShapes.loc[routeShapes['shape_id']=='M-W-P-Z-2'].sort_values('vertex_ind')) # Zetland to The Bays Precinct
route3bh = route3bh.append(routeShapes.loc[routeShapes['shape_id']=='M-W-1'].sort_values('vertex_ind')) # The Bays Precinct to Parramatta
route3bh = route3bh.reset_index(drop=True)
route3bh['shape_pt_sequence'] = route3bh.index+1
route3bh['shape_id'] = 'M-3b-MBRA-PRMT'

route3br = routeShapes.loc[routeShapes['shape_id']=='M-W-2'].sort_values('vertex_ind') # Parramatta to The Bays Precinct
route3br = route3br.append(routeShapes.loc[routeShapes['shape_id']=='M-W-P-Z-1'].sort_values('vertex_ind')) # The Bays Precinct to Zetland
route3br = route3br.append(routeShapes.loc[routeShapes['shape_id']=='M_Z_M_1'].sort_values('vertex_ind')) # Zetland to Maroubra
route3br = route3br.reset_index(drop=True)
route3br['shape_pt_sequence'] = route3br.index+1
route3br['shape_id'] = 'M-3b-PRMT-MBRA'

route3b = route3bh.append(route3br)
route3b = route3b[['shape_id','shape_lat','shape_lon','shape_pt_sequence','distance']]
route3b

           shape_id  shape_lat   shape_lon  shape_pt_sequence     distance
0    M-3b-MBRA-PRMT -33.965844  151.250771                  1     0.000000
1    M-3b-MBRA-PRMT -33.944497  151.242406                  2  2490.621707
2    M-3b-MBRA-PRMT -33.940453  151.241039                  3  2956.651676
3    M-3b-MBRA-PRMT -33.934270  151.238895                  4  3670.484049
4    M-3b-MBRA-PRMT -33.923089  151.234705                  5  4969.736715
..              ...        ...         ...                ...          ...
312  M-3b-PRMT-MBRA -33.922921  151.234844                313  2560.512017
313  M-3b-PRMT-MBRA -33.924601  151.235426                314  2754.412480
314  M-3b-PRMT-MBRA -33.933906  151.238936                315  3836.355092
315  M-3b-PRMT-MBRA -33.945197  151.242877                316  5140.561752
316  M-3b-PRMT-MBRA -33.965728  151.250959                317  7537.067133

[600 rows x 5 columns]

In [8]:
# Metro route 4a (Kogarah - Bankstown - Parramatta - Bella Vista - Tallawong)

route4ah = routeShapes.loc[routeShapes['shape_id']=='M-P-B-K-2'].sort_values('vertex_ind') # Kogarah to Parramatta
route4ah = route4ah.append(routeShapes.loc[routeShapes['shape_id']=='M-P-1'].sort_values('vertex_ind')) # Parramatta to M7 before Wye
route4ah = route4ah.append(routeShapes.loc[routeShapes['shape_id']=='M-P-BV-T-1'].sort_values('vertex_ind')) # M7 before Wye to Bella Vista and Tallawong 
route4ah = route4ah.reset_index(drop=True)
route4ah['shape_pt_sequence'] = route4ah.index+1
route4ah['shape_id'] = 'M-4a-KGRH-TLWG'

route4ar = routeShapes.loc[routeShapes['shape_id']=='M-P-BV-T-2'].sort_values('vertex_ind') # Tallawong to Bella Vista and M7 before Wye
route4ar = route4ar.append(routeShapes.loc[routeShapes['shape_id']=='M-P-2'].sort_values('vertex_ind')) # M7 before Wye to Parramatta
route4ar = route4ar.append(routeShapes.loc[routeShapes['shape_id']=='M-P-B-K-1'].sort_values('vertex_ind')) # Parramatta to Kogarah
route4ar = route4ar.reset_index(drop=True)
route4ar['shape_pt_sequence'] = route4ar.index+1
route4ar['shape_id'] = 'M-4a-TLWG-KGRH'

route4a = route4ah.append(route4ar)
route4a = route4a[['shape_id','shape_lat','shape_lon','shape_pt_sequence','distance']]
route4a

           shape_id  shape_lat   shape_lon  shape_pt_sequence      distance
0    M-4a-KGRH-TLWG -33.963351  151.132043                  1      0.000000
1    M-4a-KGRH-TLWG -33.961724  151.132545                  2    186.320749
2    M-4a-KGRH-TLWG -33.961645  151.132559                  3    195.255805
3    M-4a-KGRH-TLWG -33.961363  151.132559                  4    226.554965
4    M-4a-KGRH-TLWG -33.961304  151.132541                  5    233.287074
..              ...        ...         ...                ...           ...
222  M-4a-TLWG-KGRH -33.959433  151.131041                223  22635.412512
223  M-4a-TLWG-KGRH -33.960545  151.132069                224  22791.193275
224  M-4a-TLWG-KGRH -33.961329  151.132579                225  22890.079604
225  M-4a-TLWG-KGRH -33.961676  151.132581                226  22928.573615
226  M-4a-TLWG-KGRH -33.963359  151.132064                227  23121.302530

[439 rows x 5 columns]

In [9]:
# Metro route 4b (Kogarah - Bankstown - Parramatta - Norwest)

route4bh = routeShapes.loc[routeShapes['shape_id']=='M-P-B-K-2'].sort_values('vertex_ind') # Kogarah to Parramatta
route4bh = route4bh.append(routeShapes.loc[routeShapes['shape_id']=='M-P-1'].sort_values('vertex_ind')) # Parramatta to M7 before Wye
route4bh = route4bh.append(routeShapes.loc[routeShapes['shape_id']=='M-P-N-1'].sort_values('vertex_ind')) # M7 before Wye to Norwest
route4bh = route4bh.reset_index(drop=True)
route4bh['shape_pt_sequence'] = route4bh.index+1
route4bh['shape_id'] = 'M-4b-KGRH-NWST'

route4br = routeShapes.loc[routeShapes['shape_id']=='M-P-N-2'].sort_values('vertex_ind') # Norwest to M7 before Wye
route4br = route4br.append(routeShapes.loc[routeShapes['shape_id']=='M-P-2'].sort_values('vertex_ind')) # M7 before Wye to Parramatta
route4br = route4br.append(routeShapes.loc[routeShapes['shape_id']=='M-P-B-K-1'].sort_values('vertex_ind')) # Parramatta to Kogarah
route4br = route4br.reset_index(drop=True)
route4br['shape_pt_sequence'] = route4br.index+1
route4br['shape_id'] = 'M-4b-NWST-KGRH'

route4b = route4bh.append(route4br)
route4b = route4b[['shape_id','shape_lat','shape_lon','shape_pt_sequence','distance']]
route4b

           shape_id  shape_lat   shape_lon  shape_pt_sequence      distance
0    M-4b-KGRH-NWST -33.963351  151.132043                  1      0.000000
1    M-4b-KGRH-NWST -33.961724  151.132545                  2    186.320749
2    M-4b-KGRH-NWST -33.961645  151.132559                  3    195.255805
3    M-4b-KGRH-NWST -33.961363  151.132559                  4    226.554965
4    M-4b-KGRH-NWST -33.961304  151.132541                  5    233.287074
..              ...        ...         ...                ...           ...
137  M-4b-NWST-KGRH -33.959433  151.131041                138  22635.412512
138  M-4b-NWST-KGRH -33.960545  151.132069                139  22791.193275
139  M-4b-NWST-KGRH -33.961329  151.132579                140  22890.079604
140  M-4b-NWST-KGRH -33.961676  151.132581                141  22928.573615
141  M-4b-NWST-KGRH -33.963359  151.132064                142  23121.302530

[293 rows x 5 columns]

In [10]:
# Metro route 5 (Epping - Parramatta - WSI Airport)

route5h = routeShapes.loc[routeShapes['shape_id']=='M-P-E-2'].sort_values('vertex_ind') # Epping to Parramatta
route5h = route5h.append(routeShapes.loc[routeShapes['shape_id']=='M-P-WSA-1'].sort_values('vertex_ind')) # Parramatta to WSIA
route5h = route5h.reset_index(drop=True)
route5h['shape_pt_sequence'] = route5h.index+1
route5h['shape_id'] = 'M-5-EPNG-WSIA'

route5r = routeShapes.loc[routeShapes['shape_id']=='M-P-WSA-2'].sort_values('vertex_ind') # WSIA to Parramatta
route5r = route5r.append(routeShapes.loc[routeShapes['shape_id']=='M-P-E-1'].sort_values('vertex_ind')) # Parramatta to Epping
route5r = route5r.reset_index(drop=True)
route5r['shape_pt_sequence'] = route5r.index+1
route5r['shape_id'] = 'M-5-WSIA-EPNG'

route5 = route5h.append(route5r)
route5 = route5[['shape_id','shape_lat','shape_lon','shape_pt_sequence','distance']]
route5

         shape_id  shape_lat   shape_lon  shape_pt_sequence      distance
0   M-5-EPNG-WSIA -33.774037  151.082602                  1      0.000000
1   M-5-EPNG-WSIA -33.772219  151.081699                  2    218.334715
2   M-5-EPNG-WSIA -33.772094  151.081493                  3    241.928292
3   M-5-EPNG-WSIA -33.772011  151.081223                  4    268.518307
4   M-5-EPNG-WSIA -33.771836  151.078136                  5    555.185242
..            ...        ...         ...                ...           ...
82  M-5-WSIA-EPNG -33.771819  151.078107                 83   9420.851758
83  M-5-WSIA-EPNG -33.771965  151.080807                 84   9671.444588
84  M-5-WSIA-EPNG -33.772046  151.081760                 85   9760.169545
85  M-5-WSIA-EPNG -33.772229  151.082079                 86   9796.087103
86  M-5-WSIA-EPNG -33.773989  151.082880                 87  10004.890905

[164 rows x 5 columns]

In [11]:
# Metro route 6

route6h = routeShapes.loc[routeShapes['shape_id']=='M-SM-TW-2'].sort_values('vertex_ind') # Tallawong to St Marys
route6h = route6h.append(routeShapes.loc[routeShapes['shape_id']=='M-NS-RL-1'].sort_values('vertex_ind')) # St Marys to Macarthur
route6h = route6h.reset_index(drop=True)
route6h['shape_pt_sequence'] = route6h.index+1
route6h['shape_id'] = 'M-6-TLWG-MCTR'

route6r = routeShapes.loc[routeShapes['shape_id']=='M-NS-RL-2'].sort_values('vertex_ind') # Macarthur to St Marys
route6r = route6r.append(routeShapes.loc[routeShapes['shape_id']=='M-SM-TW-1'].sort_values('vertex_ind')) # St Marys to Tallawong
route6r = route6r.reset_index(drop=True)
route6r['shape_pt_sequence'] = route6r.index+1
route6r['shape_id'] = 'M-6-MCTR-TLWG'

route6 = route6h.append(route6r)
route6 = route6[['shape_id','shape_lat','shape_lon','shape_pt_sequence','distance']]
route6

          shape_id  shape_lat   shape_lon  shape_pt_sequence      distance
0    M-6-TLWG-MCTR -33.691677  150.906184                  1      0.000000
1    M-6-TLWG-MCTR -33.692273  150.904245                  2    191.555912
2    M-6-TLWG-MCTR -33.692588  150.903055                  3    307.335680
3    M-6-TLWG-MCTR -33.694035  150.900355                  4    604.667701
4    M-6-TLWG-MCTR -33.696500  150.894284                  5   1230.525740
..             ...        ...         ...                ...           ...
112  M-6-MCTR-TLWG -33.694004  150.900331                113  16564.512751
113  M-6-MCTR-TLWG -33.692566  150.903046                114  16862.429858
114  M-6-MCTR-TLWG -33.692165  150.904074                115  16967.628249
115  M-6-MCTR-TLWG -33.691599  150.905834                116  17142.490401
116  M-6-MCTR-TLWG -33.691512  150.906117                117  17170.484901

[246 rows x 5 columns]

In [12]:
# Parramatta light rail - phase 1

routePLR1h = routeShapes.loc[routeShapes['shape_id']=='20560162'].sort_values('vertex_ind')
routePLR1h = routePLR1h.reset_index(drop=True)
routePLR1h['shape_pt_sequence'] = routePLR1h.index+1
routePLR1h['shape_id'] = 'L-PLR1-WSMD-CLFD'

routePLR1r = routeShapes.loc[routeShapes['shape_id']=='20560161'].sort_values('vertex_ind')
routePLR1r = routePLR1r.reset_index(drop=True)
routePLR1r['shape_pt_sequence'] = routePLR1r.index+1
routePLR1r['shape_id'] = 'L-PLR1-CLFD-WSMD'

routePLR2h = routeShapes.loc[routeShapes['shape_id']=='20560171'].sort_values('vertex_ind')
routePLR2h = routePLR2h.reset_index(drop=True)
routePLR2h['shape_pt_sequence'] = routePLR2h.index+1
routePLR2h['shape_id'] = 'L-PLR2-WSUN-OLYP'

routePLR2r = routeShapes.loc[routeShapes['shape_id']=='20560172'].sort_values('vertex_ind')
routePLR2r = routePLR2r.reset_index(drop=True)
routePLR2r['shape_pt_sequence'] = routePLR2r.index+1
routePLR2r['shape_id'] = 'L-PLR2-OLYP-WSUN'

routePLR = routePLR1h.append(routePLR1r).append(routePLR2h).append(routePLR2r)
routePLR = routePLR[['shape_id','shape_lat','shape_lon','shape_pt_sequence','distance']]
routePLR

             shape_id  shape_lat   shape_lon  shape_pt_sequence     distance
0    L-PLR1-WSMD-CLFD -33.807762  150.987348                  1     0.000000
1    L-PLR1-WSMD-CLFD -33.807612  150.987430                  2    18.263214
2    L-PLR1-WSMD-CLFD -33.807528  150.987475                  3    28.421620
3    L-PLR1-WSMD-CLFD -33.807497  150.987490                  4    32.195420
4    L-PLR1-WSMD-CLFD -33.807389  150.987558                  5    45.720191
..                ...        ...         ...                ...          ...
133  L-PLR2-OLYP-WSUN -33.814419  151.034087                134  9038.201502
134  L-PLR2-OLYP-WSUN -33.814105  151.032203                135  9216.033245
135  L-PLR2-OLYP-WSUN -33.813931  151.030571                136  9368.329815
136  L-PLR2-OLYP-WSUN -33.813694  151.028725                137  9541.286914
137  L-PLR2-OLYP-WSUN -33.813463  151.026643                138  9735.760777

[760 rows x 5 columns]

In [13]:
# Train route T2 extension (City - Leppington - WS Aerotropolis)

routeT2h = routeShapes.loc[routeShapes['shape_id']=='2-T2-sj2-22.76.H'].sort_values('vertex_ind') # City circle to Leppington 
routeT2h = routeT2h.append(routeShapes.loc[routeShapes['shape_id']=='LP-C-B2'].sort_values('vertex_ind')) # Leppington to Aerotropolis connection
routeT2h = routeT2h.append(routeShapes.loc[routeShapes['shape_id']=='M-SW-RL-2'].sort_values('vertex_ind')) # Leppington to Aerotropolis
routeT2h = routeT2h.reset_index(drop=True)
routeT2h['shape_pt_sequence'] = routeT2h.index+1
routeT2h['shape_id'] = 'T2-CTYC-WSAR'

routeT2r = routeShapes.loc[routeShapes['shape_id']=='M-SW-RL-1'].sort_values('vertex_ind') # Aerotropolis to Leppington
routeT2r = routeT2r.append(routeShapes.loc[routeShapes['shape_id']=='LP-C-B1'].sort_values('vertex_ind')) # Aerotropolis to Leppington connection
routeT2r = routeT2r.append(routeShapes.loc[routeShapes['shape_id']=='2-T2-sj2-22.9.R'].sort_values('vertex_ind')) # Leppington to City circle
routeT2r = routeT2r.reset_index(drop=True)
routeT2r['shape_pt_sequence'] = routeT2r.index+1
routeT2r['shape_id'] = 'T2-WSAR-CTYC'

routeT2 = routeT2h.append(routeT2r)
routeT2 = routeT2[['shape_id','shape_lat','shape_lon','shape_pt_sequence','distance']]
routeT2

         shape_id  shape_lat   shape_lon  shape_pt_sequence      distance
0    T2-CTYC-WSAR -33.884308  151.207152                  1      0.000000
1    T2-CTYC-WSAR -33.884000  151.207376                  2     39.954442
2    T2-CTYC-WSAR -33.883808  151.207504                  3     64.320265
3    T2-CTYC-WSAR -33.883688  151.207568                  4     78.887213
4    T2-CTYC-WSAR -33.883480  151.207696                  5    104.818387
..            ...        ...         ...                ...           ...
786  T2-WSAR-CTYC -33.885328  151.205744                787  50798.881086
787  T2-WSAR-CTYC -33.884916  151.206192                788  50860.570297
788  T2-WSAR-CTYC -33.884684  151.206400                789  50892.700348
789  T2-WSAR-CTYC -33.884360  151.206672                790  50936.569192
790  T2-WSAR-CTYC -33.884120  151.206848                791  50967.772514

[1680 rows x 5 columns]

In [14]:
futureRailRouteShapes = route1.append(route2)
futureRailRouteShapes = futureRailRouteShapes.append(route3a)
futureRailRouteShapes = futureRailRouteShapes.append(route3b)
futureRailRouteShapes = futureRailRouteShapes.append(route4a)
futureRailRouteShapes = futureRailRouteShapes.append(route4b)
futureRailRouteShapes = futureRailRouteShapes.append(route5)
futureRailRouteShapes = futureRailRouteShapes.append(route6)
futureRailRouteShapes = futureRailRouteShapes.append(routePLR)
futureRailRouteShapes = futureRailRouteShapes.append(routeT2)
futureRailRouteShapes.reset_index(drop=True, inplace=True)
futureRailRouteShapes['shape_id'].unique()

array(['M-1-LVPL-TLWG', 'M-1-TLWG-LVPL', 'M-2-BKTN-EPNG', 'M-2-EPNG-BKTN',
       'M-3a-MBRA-WSIA', 'M-3a-WSIA-MBRA', 'M-3b-MBRA-PRMT',
       'M-3b-PRMT-MBRA', 'M-4a-KGRH-TLWG', 'M-4a-TLWG-KGRH',
       'M-4b-KGRH-NWST', 'M-4b-NWST-KGRH', 'M-5-EPNG-WSIA',
       'M-5-WSIA-EPNG', 'M-6-TLWG-MCTR', 'M-6-MCTR-TLWG',
       'L-PLR1-WSMD-CLFD', 'L-PLR1-CLFD-WSMD', 'L-PLR2-WSUN-OLYP',
       'L-PLR2-OLYP-WSUN', 'T2-CTYC-WSAR', 'T2-WSAR-CTYC'], dtype=object)

In [15]:
futureRailRouteShapes = futureRailRouteShapes.sort_values(['shape_id','shape_pt_sequence'], ascending=[True,True])
futureRailRouteShapes['geopy_dist'] = np.nan
for i in range(len(futureRailRouteShapes)):
    if futureRailRouteShapes['shape_pt_sequence'][i] == 1:
        futureRailRouteShapes['geopy_dist'][i] = 0
    else:
        p1 = (futureRailRouteShapes['shape_lat'][i-1],futureRailRouteShapes['shape_lon'][i-1]) 
        p2 = (futureRailRouteShapes['shape_lat'][i],futureRailRouteShapes['shape_lon'][i])
        futureRailRouteShapes['geopy_dist'][i] = geo.sphere.haversine_distance(p1,p2)
futureRailRouteShapes['cum_dist'] = futureRailRouteShapes.groupby(['shape_id'])['geopy_dist'].cumsum()
futureRailRouteShapes.head()

/Users/hemarayaprolu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/hemarayaprolu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

,shape_id,shape_lat,shape_lon,shape_pt_sequence,distance,geopy_dist,cum_dist
6236,L-PLR1-CLFD-WSMD,-33.781953,151.047190,1,0.000000,0.000000,0.000000
6237,L-PLR1-CLFD-WSMD,-33.782527,151.046673,2,79.718193,80.182320,80.182320
6238,L-PLR1-CLFD-WSMD,-33.782692,151.046507,3,103.610511,24.469537,104.651857
6239,L-PLR1-CLFD-WSMD,-33.782793,151.046403,4,118.354174,15.130452,119.782310
6240,L-PLR1-CLFD-WSMD,-33.782982,151.046214,5,145.658987,27.910204,147.692514

In [16]:
futureRailRouteShapes.drop(['distance','geopy_dist'], axis=1, inplace=True)
futureRailRouteShapes.columns = ['shape_id','shape_pt_lat','shape_pt_lon','shape_pt_sequence','shape_dist_traveled']
futureRailRouteShapes.head()

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
6236,L-PLR1-CLFD-WSMD,-33.781953,151.047190,1,0.000000
6237,L-PLR1-CLFD-WSMD,-33.782527,151.046673,2,80.182320
6238,L-PLR1-CLFD-WSMD,-33.782692,151.046507,3,104.651857
6239,L-PLR1-CLFD-WSMD,-33.782793,151.046403,4,119.782310
6240,L-PLR1-CLFD-WSMD,-33.782982,151.046214,5,147.692514

In [17]:
futureRailRouteShapes.to_csv('./output/future/shapes.txt', index=False)

## Edit current lines

In [10]:
# Current GTFS

shapes = pd.read_csv('./input/gtfs_static_8jul2020/shapes.txt')
routes = pd.read_csv('./input/gtfs_static_8jul2020/routes.txt')
trips = pd.read_csv('./input/gtfs_static_8jul2020/trips.txt')
stoptimes = pd.read_csv('./input/gtfs_static_8jul2020/stop_times.txt')
calendar = pd.read_csv('./input/gtfs_static_8jul2020/calendar.txt')
calendardates = pd.read_csv('./input/gtfs_static_8jul2020/calendar_dates.txt')
stops = pd.read_csv('./input/gtfs_static_8jul2020/stops.txt')

In [11]:
# Remove existing metro line (but keep stops)

print(len(routes['route_id']))
routes = routes.loc[routes['route_desc']!='Sydney Metro Network']
print(len(routes['route_id']))

print(len(trips))
trips['route_id'] = trips['route_id'].astype(str)
routes['route_id'] = routes['route_id'].astype(str)
trips = trips.loc[trips['route_id'].isin(routes['route_id'])]
print(len(trips))

print(len(stoptimes))
stoptimes['trip_id'] = stoptimes['trip_id'].astype(str)
trips['trip_id'] = trips['trip_id'].astype(str)
stoptimes = stoptimes.loc[stoptimes['trip_id'].isin(trips['trip_id'])]
print(len(stoptimes))

print(len(shapes))
shapes['shape_id'] = shapes['shape_id'].astype(str)
trips['shape_id'] = trips['shape_id'].astype(str)
shapes = shapes.loc[shapes['shape_id'].isin(trips['shape_id'])]
print(len(shapes))

print(len(calendar))
calendar['service_id'] = calendar['service_id'].astype(str)
trips['service_id'] = trips['service_id'].astype(str)
calendar = calendar.loc[calendar['service_id'].isin(trips['service_id'])]
print(len(calendar))

print(len(calendardates))
calendardates['service_id'] = calendardates['service_id'].astype(str)
trips['service_id'] = trips['service_id'].astype(str)
calendardates = calendardates.loc[calendardates['service_id'].isin(trips['service_id'])]
print(len(calendardates))

6613
6612
166978
152267
4624043
4432800
8273339
8272487
2303
2159
27489
25779

In [12]:
# Remove existing T2 (but keep stops)

print(len(routes['route_id']))
routes = routes.loc[routes['route_id'].str.contains('T2')==False]
print(len(routes['route_id']))

print(len(trips))
trips['route_id'] = trips['route_id'].astype(str)
routes['route_id'] = routes['route_id'].astype(str)
trips = trips.loc[trips['route_id'].isin(routes['route_id'])]
print(len(trips))

print(len(stoptimes))
stoptimes['trip_id'] = stoptimes['trip_id'].astype(str)
trips['trip_id'] = trips['trip_id'].astype(str)
stoptimes = stoptimes.loc[stoptimes['trip_id'].isin(trips['trip_id'])]
print(len(stoptimes))

print(len(shapes))
shapes['shape_id'] = shapes['shape_id'].astype(str)
trips['shape_id'] = trips['shape_id'].astype(str)
shapes = shapes.loc[shapes['shape_id'].isin(trips['shape_id'])]
print(len(shapes))

print(len(calendar))
calendar['service_id'] = calendar['service_id'].astype(str)
trips['service_id'] = trips['service_id'].astype(str)
calendar = calendar.loc[calendar['service_id'].isin(trips['service_id'])]
print(len(calendar))

print(len(calendardates))
calendardates['service_id'] = calendardates['service_id'].astype(str)
trips['service_id'] = trips['service_id'].astype(str)
calendardates = calendardates.loc[calendardates['service_id'].isin(trips['service_id'])]
print(len(calendardates))

6612
6611
152267
147660
4432800
4332661
8272487
8198121
2159
2159
25779
25779

In [13]:
routes.to_csv('./output/current_edited/routes.txt', index=False)
shapes.to_csv('./output/current_edited/shapes.txt', index=False)
trips.to_csv('./output/current_edited/trips.txt', index=False)
stops.to_csv('./output/current_edited/stops.txt', index=False)
stoptimes.to_csv('./output/current_edited/stop_times.txt', index=False)
calendar.to_csv('./output/current_edited/calendar.txt', index=False)
calendardates.to_csv('./output/current_edited/calendar_dates.txt', index=False)